# Generated by Django 2.1 on 2018-08-14 04:33

from django.db import migrations, models


def initial_entry(apps, schema_editor):
    Tenant = apps.get_model("sharedtenant","Tenant")
    tenant_created = Tenant.objects.create(subdomain="localhost")



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(initial_entry)
    ]
