# Generated by Django 2.1 on 2018-08-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedtenant', '0002_tenantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
