# Generated by Django 2.0.3 on 2018-03-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180322_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_class',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
