# Generated by Django 2.1 on 2018-08-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedtenant', '0001_initial'),
        ('tasks', '0006_auto_20180404_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sharedtenant.Tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sharedtenant.Tenant'),
            preserve_default=False,
        ),
    ]
